language: node_js
node_js:
  - 'node'

cache: npm

script:
  - export PUBLIC_URL=/react-snake-game/
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
env:
  global:
    secure: HnoKY3UuGRDJPYUFArFZpDVjD2rUCkgoiPex6sRGQ5gCZ8D6gMnriRVlKxtSywphAxoAsLY87YnQg4y4RxZ4Xv0jbhE21DlXmWrTgIAeEbgTnko4OgjBqz74Irsg/y9qecyScwb6qd+npazhsouFl1EnjwuuMqsGk/mmmWI4KKvW4fwZrkZLBgrCqjJ6KYCvYLkHMbC5eZdBoecEcUB5yKhKiPPw6A7yX/NawaeqZOA+zIfA2jtvFAD1hKPugI6crUkofugmy18mpLL692jIw4tmCeeoCt2zmtrAQKaCG6eeUvIutXdaiNScL+3s/2wtC0ciQ/NADOP12QGeYbbFozx0aVnhekB8V2oWasg7spkHcdUVf0nkMLVNiXqnev3q0k9rb/Ui/+KoBpnv7xxlvbCnRCGnxaPooBWYJe3H5Bf8gTMKXfXgHjEBXJOlVvYSnLdMf+0iF77kCZlOkvGc2k/xquVn79ka/ng43vvdsO1kUUDrFbBATWCeUsNxz0zT6OySmixaO5tgH90KH2QBLZnnyyuFfS91uwoj8Za35hjG7YJkOmTiPyXG7aDzdLSdGRLSi6UNJ7UUqkVjskS+bPL1DMAT47eBytiZWHq0hrmJNO0/J1XeWHjDDJKwKqKBCWWnM4OH4xjSFGa0TaXwL0tQhnHioTKt/nu6tciJtCI=
